### ISSUE TITLE
Need For clarification: Add full installation instructions.

### ISSUE THREAD

**Issue by mwip** [rlpowell/todo-text-stuff#20]
Outing myself as a total ruby noob here. However, I appreciate this totally cool project!
Anyways, I am not able to get it to run. Getting the follwoing error:
```
Traceback (most recent call last):
        2: from /home/USER/.todo.actions.d/ice_recur:3:in `<main>'
        1: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ice_cube (LoadError)
```
Running on Arch and freshly installed ruby. It seems that there are some dependencies missing. 
I (and probably potential other users) would appreciate a clarification of the dependencies and installation procedure. 
Thanks so much. 
Please let me know, if I could test anything.

**Comment by mwip** [comment]
solved by merging #21
